logging:
  level:
    root: info
    com :
      amazonaws :
        util :
          EC2MetadataUtils : error
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email-username}
    password: ${email-password}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    port: 6379
    host: localhost
  #    password: ${redis-password}
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
      url: ${MY_LOCAL_URL}
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: ${LOCAL_MYSQL_PW}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      data-locations: classpath*:sql/init.sql
  batch:
    job:
      enabled: false # 시작과 동시에 실행되는 건 방지
    jdbc:
      schema: classpath:org/springframework/batch/core/schema-mysql.sql

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESSKEY}
      secret-key: ${S3_SECRETKEY}
    s3:
      bucket: ${S3_BUCKET}
      endpoint: ${S3_ENDPOINT}
    region:
      static: ${S3_REGION}
    stack:
      auto: false