const dummyPets = [
  {
    id: 1,
    petName: '달콩일',
    petGender: 'male',
    breed: '요크 셔테리어',
    petSize: 'DOG_S',
    petAge: 9,
    neutred: true,
    aboutDog: '처음엔 겁이 많지만 친해지만 같이 잘 놀아요!',
    petImage: 'https://ibb.co/mNQ4D7F',
  },
  {
    id: 2,
    petName: '달콩이',
    petGender: 'female',
    breed: '요크 셔테리어',
    petSize: 'DOG_S',
    petAge: 4,
    neutred: false,
    aboutDog: '친구를 좋아하는 귀여운 요크셔 입니다~~~!!!',
    petImage: 'https://ibb.co/XVG3JKh',
  },
  {
    id: 3,
    petName: '둥일',
    petGender: 'male',
    breed: '말티즈',
    petSize: 'DOG_S',
    petAge: 9,
    neutred: true,
    aboutDog: '낯가림이 많고 산책을 오래하면 안걸음.',
    petImage:
      'https://i.ibb.co/Rj5b3xs/Kakao-Talk-Photo-2023-01-12-00-46-38.jpg',
  },
  {
    id: 4,
    petName: '둥이',
    petGender: 'male',
    breed: '말티즈',
    petSize: 'DOG_S',
    petAge: 9,
    neutred: true,
    aboutDog: '낯가림이 많고 산책을 오래하면 안걸음.',
    petImage:
      'https://i.ibb.co/Rj5b3xs/Kakao-Talk-Photo-2023-01-12-00-46-38.jpg',
  },
  {
    id: 5,
    petName: '둥삼',
    petGender: 'male',
    breed: '말티즈',
    petSize: 'DOG_S',
    petAge: 9,
    neutred: true,
    aboutDog: '낯가림이 많고 산책을 오래하면 안걸음.',
    petImage:
      'https://i.ibb.co/Rj5b3xs/Kakao-Talk-Photo-2023-01-12-00-46-38.jpg',
  },
  {
    id: 6,
    petName: '둥사',
    petGender: 'male',
    breed: '말티즈',
    petSize: 'DOG_S',
    petAge: 9,
    neutred: true,
    aboutDog: '낯가림이 많고 산책을 오래하면 안걸음.',
    petImage:
      'https://i.ibb.co/Rj5b3xs/Kakao-Talk-Photo-2023-01-12-00-46-38.jpg',
  },
  {
    id: 7,
    petName: '둥오',
    petGender: 'male',
    breed: '말티즈',
    petSize: 'DOG_S',
    petAge: 9,
    neutred: true,
    aboutDog: '낯가림이 많고 산책을 오래하면 안걸음.',
    petImage:
      'https://i.ibb.co/Rj5b3xs/Kakao-Talk-Photo-2023-01-12-00-46-38.jpg',
  },
];

export default dummyPets;
